### ISSUE TITLE
Tratamento de erros na entrada do usuario

### ISSUE THREAD

**Issue by laisbastosbg** [btwhelena/Swift-Challenge#1]
Ao tentar converter a entrada do usuário para inteiro não tem nenhum tratamento de erro o que pode levar o programa a crashar caso o usuário entre com um valor que não seja possível converter

https://github.com/btwhelena/Swift-Challenge/blob/a540f08104cd97cc8b14e196eb9360499bdf14c3/Sources/Hello/main.swift#L174-L177

O leitura do input poderia ficar dentro de um laço while e só sair quando o valor for válido:

```swift
var isInputValid = false
var input: String?

while !isInputValid {
    input = readLine()
    if let intInput = Int(input!) {
        isInputValid = true
    } else {
        print("Por favor insira um valor inteiro")
    }
}
```

**Comment by btwhelena** [comment]
Obrigada pela sugestão, Lais! Irei implementá-la assim que possível ✨
