### ISSUE TITLE
Função de inteiros recebendo strings

### ISSUE THREAD

**Issue by mill3na** [btwhelena/Swift-Challenge#2]
https://github.com/btwhelena/Swift-Challenge/blob/a540f08104cd97cc8b14e196eb9360499bdf14c3/Sources/Hello/main.swift#L134-L143

Oi, Helena! Parabéns pelo seu programa, está bem organizado e limpo! 

Só uma sugestão de mudança: a verificação de input nessa função faz sentido, mas não surtiu efeito nesse caso. Ele recebe um int, mas aceita strings (e retorna resultados). Você pode colocar um laço que só interrompa se a entrada for válida (como um while) :)

Qualquer dúvida, pode me chamar!

<img width="585" alt="Captura de Tela 2022-03-31 às 09 32 48" src="https://user-images.githubusercontent.com/58698807/161056118-b63fbae5-9ad8-4a47-8a2a-d265a0581436.png">

**Comment by btwhelena** [comment]
Oii Milena! Perfeito, irei corrigir em breve 🥰 Obrigada pela sugestão
