### ISSUE TITLE
Sugestão de melhoria na leitura do código

### ISSUE THREAD

**Issue by ThiagoHBA** [btwhelena/Swift-Challenge#3]
E aí Helena, tudo bem? Queria te dar uma sugestão que talvez vá facilitar pra ti e para outras pessoas que poderão vir para ler o código. Vi que nos sumários, onde escolhemos o ingrediente, por exemplo, utiliza-se uma estrutura de `switch/case` para identificar qual foi a resposta do usuário: 

```Swift
switch intOption {
    
  case 0:
    print("➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖")
    print("✅ You selected Wheat Flour!")
    readGrams()
    conversor(input: intWeight)
    
  case 1:
    print("➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖")
    print("➡️ You selected Sugar!")
    readGrams()
    conversor(input: intWeight)
...
```
Essa abordagem é válida e também funcional, porém, pode vir a dificultar em uma leitura futura ou na aplicação de uma nova feature. Uma substituição possível seria com a utilização de [Enumerations](https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html), onde a gente poderia "Transferir" essa responsabilidade de dizer qual número corresponde a qual elemento, como por exemplo: 

```Swift
enum Ingredients : Int{
    case wheatFlour = 0
    case sugar = 1
    case cornStart = 2
}

let ingredient = Ingredients(rawValue: 2)

print(ingredient!)
```

Resultado do print: 
```cornStart```

Possivelmente ainda seria necessário o uso de uma estrutura de decisão para direcionar o fluxo daquela resposta, porém, essa estrutura ficaria bem mais fácil de ser lida.

**Comment by btwhelena** [comment]
Ameeeeei a sugestão 🥰 Não sabia dessa estrutura, acho que se aplica bem a esse problema

Realmente fica bem mais limpo o código, muito obrigada pelo feedback amigo ✨
