### ISSUE TITLE
Sobre o programinha

### ISSUE THREAD

**Issue by CapistranoIFCE** [btwhelena/Swift-Challenge#5]
Helena, queria citar alguns pontos. Mas a galera já citou alguns que eu vi. 
Queria parabenizar, pois esse programa também serviria para mim, pois sou um desastre na cozinha!

**Comment by btwhelena** [comment]
HAHAHAHAHA Amigo eu não tenho balança então quando a receita era em gramas eu cagava tudo medindo no "olhômetro" 🤡😆

**Comment by btwhelena** [comment]
Muito obrigada pelo elogio, fico feliz demais que você gostou 💖🥺
