### ISSUE TITLE
Comentário e sugestão

### ISSUE THREAD

**Issue by Natalialocatelli** [btwhelena/Swift-Challenge#6]
Oi Helena, tudo bem? Amei o seu projeto, amo cozinhar e achei de fato mt útil, entretanto, notei que na opção para digitar as gramas ele aceita letras e caracteres especias sem mostrar nenhum aviso de erro, com isso, tenho uma sugestão para que tenha um aviso pedindo para que inserisse um novo valor válido, assim como você fez para a seleção de ingredientes inválidos.

**Comment by btwhelena** [comment]
Oie Natalia!

Muito pertinente sua observação, obrigada pelo feedback, irei corrigir em breve 💞✨
