### ISSUE TITLE
Possível nova feature

### ISSUE THREAD

**Issue by yago-marques** [btwhelena/Swift-Challenge#7]
Muuito massa o seu projeto!

tenho uma ideia de uma possível nova feature:

- Vi que vc usou um JSON local para mockar seus dados, seria legal estudar uma maneira de dar a possibilidade do usuário mudar as receitas conforme sua escolha

**Comment by btwhelena** [comment]
Amigo, irado demais! Vou estudar essa possibilidade e ver como faço para implementar 🧐
