### ISSUE TITLE
Parabéns

### ISSUE THREAD

**Issue by nillias** [btwhelena/Swift-Challenge#8]
Oi Helena, parabéns pelo programa! Ele ficou muito bonito, mesmo sendo no terminal o uso de emojis deu uma outra vida, amei. Sua ideia também é muito útil, gostei demais.

**Comment by btwhelena** [comment]
Ai muitooo obrigada 🥺💞

Usei os emojis como uma tentativa de quebrar aquele visual mais cru do terminal e deixar o usuário mais a vontade, visto que são bem familiarizados com emojis. Foi uma forma do programa parecer mais familiar e acolhedor
